### ISSUE TITLE
Compilation error in lexical-core-0.7.4

### ISSUE THREAD

**Issue by feiss** [mblarsen/mbox2imap#2]
I get multiple errors during `cargo build`, of this kind:

![image](https://user-images.githubusercontent.com/359872/160565749-83498ba7-dfca-44ac-a076-67ab9b9e30db.png)

```
rustc 1.58.1 (db9d1b20b 2022-01-20)
cargo 1.58.0 (f01b232bc 2022-01-19)
```

**Comment by mblarsen** [comment]
Hmm, curious to what dependency is causing this. This is is not in `mbox2imap` code.

At first glance it seems to be `lexical-core`

**Comment by feiss** [comment]
After some investigation, the specific version of `lexical-core` that is being used is broken. This thread helped me to fix it: https://github.com/rust-lang/rust/issues/81654
